# GSSAPI options
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
GSSAPIStrictAcceptorCheck yes
GSSAPIKeyExchange yes

LogLevel DEBUG3

# Fetch S4U tickets for admin
Match user BOT-*
    GSSAPIAllowS4U2Self 5m
    GSSAPIProxyS4U2Services HTTP/ipa.example.org

