[sssd]
services = nss, pam, ifp, ssh, sudo
domains = example.org
debug_level = 0xfff0

[domain/example.org]
debug_level = 0xfff0
id_provider = ipa
ipa_server = ipa.example.org
ipa_domain = example.org
ipa_hostname = staging.example.org
krb5_realm = EXAMPLE.ORG
ldap_tls_cacert = /etc/ipa/ca.crt

[pam]
debug_level = 0xfff0
pam_gssapi_services = sudo, sudo-i

[sudo]
debug_level = 0xfff0

[nss]
debug_level = 0xfff0
