[libdefaults]
  default_realm = EXAMPLE.ORG
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
  ticket_lifetime = 24h
  forwardable = true
  default_ccache_name = DIR:/tmp/krb5cc_%{uid}
  dns_canonicalize_hostname = false

[realms]
  EXAMPLE.ORG = {
    kdc = ipa.example.org
    admin_server = ipa.example.org
    pkinit_anchors = FILE:/certs/tmp/ca-bundle.crt
  }

[domain_realm]
  .example.org = EXAMPLE.ORG
  example.org = EXAMPLE.ORG
